name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/rust.yml

  coverage:
    needs: build
    uses: ./.github/workflows/coverage.yml

  release:
    needs: [build, coverage]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml
