name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/rust.yml

  # coverage:
  #   needs: build
  #   uses: ./.github/workflows/coverage.yml
