name: Release

on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-release
      run: cargo install cargo-release
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cargo release --execute --no-confirm --no-publish --no-push --no-tag --no-verify
        VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[0].version')
        git tag -a "v$VERSION" -m "Release v$VERSION"
        git push origin "v$VERSION"
    
    - name: Build Release
      run: cargo build --release
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/gget
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
